package com.yuan.www.model;

import java.io.Serializable;
import java.util.Date;

public class Examinee implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Override
	public String toString() {
		return "Examinee [id=" + id + ", name=" + name + ", password="
				+ password + ", studentId=" + studentId + ", classNum="
				+ classNum + ", avater=" + avater + ", loginTime=" + loginTime
				+ ", tel=" + tel + ", nationality=" + nationality + ", height="
				+ height + ", weight=" + weight + ", school=" + school
				+ ", sex=" + sex + "]";
	}

	private Integer id;
	private String name;
	private String password;
	private Integer studentId;
	private Integer classNum;
	private String avater;
	private Date loginTime;
	private String tel;
	private String nationality;
	private Integer height;
	private Double weight;
	private String school;
	private String sex;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getStudentId() {
		return studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public Integer getClassNum() {
		return classNum;
	}

	public void setClassNum(Integer classNum) {
		this.classNum = classNum;
	}

	public String getAvater() {
		return avater;
	}

	public void setAvater(String avater) {
		this.avater = avater;
	}

	public Date getLoginTime() {
		return loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getNationality() {
		return nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinee.nationality
	 * 
	 * @param nationality
	 *            the value for tb_examinee.nationality
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinee.height
	 * 
	 * @return the value of tb_examinee.height
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinee.height
	 * 
	 * @param height
	 *            the value for tb_examinee.height
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinee.weight
	 * 
	 * @return the value of tb_examinee.weight
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public Double getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinee.weight
	 * 
	 * @param weight
	 *            the value for tb_examinee.weight
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setWeight(Double weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinee.school
	 * 
	 * @return the value of tb_examinee.school
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinee.school
	 * 
	 * @param school
	 *            the value for tb_examinee.school
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinee.sex
	 * 
	 * @return the value of tb_examinee.sex
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinee.sex
	 * 
	 * @param sex
	 *            the value for tb_examinee.sex
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}
}